export const REQUEST = 'App/MAKE_REQUEST';

export const LOAD_CONTENT_PENDING = 'App/LOAD_CONTENT_PENDING';
export const LOAD_CONTENT_SUCCESS = 'App/LOAD_CONTENT_SUCCESS';
export const LOAD_CONTENT_ERROR = 'App/LOAD_CONTENT_ERROR';

export const LOGIN_USER_PENDING = 'App/LOGIN_USER_PENDING';
export const LOGIN_USER_SUCCESS = 'App/LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'App/LOGIN_USER_ERROR';

export const LOGOUT_USER = 'App/LOGOUT_USER';
export const FORM_RESET = 'redux-form/RESET';
